### ISSUE TITLE
README BAD

### ISSUE THREAD

**Issue by pablolibo** [leed25d/geoip-vmod#6]
Hey, thanks for your geoip.

I can see the lines from:

```
,----
| import geoip;
|
| sub vcl_recv {
|     set req.http.X-Forwarded-For = client.ip;
|     set req.http.X-GeoIP = geoip.country(req.http.X-Forwarded-For)
| }
```

you need to put ";" in the last "set req.http.X-GeoIP = geoip.country(req.http.X-Forwarded-For)" like:

set req.http.X-GeoIP = geoip.country(req.http.X-Forwarded-For); 

else it doesn't work

**Comment by intelbg** [comment]
@pablolibo I have installed the module on varnish 4 and addded ; in the end of the lines but it doesn't work again - I do not see the GeoIP headers when open my test page. Also I tryed to block some countries but again does not work. I have installed geoip and geoip-devle on centos. Can you please tell why this happens and how can achieve this? Thank you in advance.
